name: "test-action"
description: "Test project"

runs:
  using: "composite"
  steps:
    - run: echo Hello!
      shell: bash
    - run: |
        docker pull hexletprojects/js_l1_brain_games4_project:release
        docker run -v `pwd`:/project/code hexletprojects/js_l1_brain_games4_project:release /bin/bash -c 'make setup test lint'
      shell: bash
